### ISSUE TITLE
dead donwload link

### ISSUE THREAD

**Issue by mavenraven** [vmware/ansible-role-ovftool#1]
Hey @tdhite, looks like https://github.com/vmware/ansible-role-ovftool/blob/master/defaults/main.yml#L27 is dead. Any chance of getting a working link? Thanks for you help!

**Comment by tompscanlan** [comment]
@mavenraven Sorry this got missed.  I'm sure you've sorted it out, but for future reference, you can always download the tool from https://www.vmware.com/support/developer/ovf/ and host it somewhere your ansible host can reach.
