### ISSUE TITLE
ansible-galaxy install ansible-role-ovftool

### ISSUE THREAD

**Issue by jimb0bmij** [vmware/ansible-role-ovftool#11]
Try to install:

ansible-galaxy install ansible-role-ovftool

- downloading role 'ansible-role-ovftool', owned by 
 [WARNING]: - ansible-role-ovftool was NOT installed successfully: Content has no field named 'owner'

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.

**Comment by tompscanlan** [comment]
@jimb0bmij try using:

    $ ansible-galaxy install vmware.ovftool
    - downloading role 'ovftool', owned by vmware
    - downloading role from https://github.com/vmware/ansible-role-ovftool/archive/master.tar.gz
    - extracting vmware.ovftool to /root/.ansible/roles/vmware.ovftool
    - vmware.ovftool (master) was installed successfully

Re-open if that doesn't work for you.
