### ISSUE TITLE
ovf_zip should be replace by ovf_bundle

### ISSUE THREAD

**Issue by nqb** [vmware/ansible-role-ovftool#13]
Currently, `README.md` and defaults variables use `ovf_zip` prefix but `unzip` module is not used anywhere. 

However, if you use a bundle in place of a zip file (like describe in #12), installation works but with some issues.

From my point of view, `ovf_zip` should be replace by `ovf_bundle`.

**Comment by nqb** [comment]
One more thing, if I extracted a zip file like "VMware-ovftool-4.4.0-15722219-lin.aarch64.zip", there is no bundle in it.

**Comment by tompscanlan** [comment]
see #12.  This project is archived, but will take PRs if you want to fix it up.

**Comment by nqb** [comment]
See my answer on #12
