### ISSUE TITLE
ansible-galaxy integration

### ISSUE THREAD

**Issue by pierreact** [vmware/ansible-role-ovftool#2]
Hello,

This doesn't show up on ansible-galaxy and cannot be retrieved by ansible-galaxy.
[WARNING]: - ansible-role-ovftool was NOT installed successfully: this role does not appear to have a meta/main.yml file.

**Comment by tompscanlan** [comment]
@pierreact It's not currently setup in ansible-galaxy.  This project has been used in the [Chaperone Project](http://github.com/vmware/chaperone) which uses google repo to collect the various needed  repositories.

I'll keep this open as we should also be pushing these to galaxy in the future.

**Comment by tompscanlan** [comment]
fixed by #5, still must host the ovftool binary in another repository
