### ISSUE TITLE
Download fail

### ISSUE THREAD

**Issue by SebastienElet** [vmware/ansible-role-ovftool#4]
The link to download ovftool seems to be broken.

```
fatal: [ovftool]: FAILED! => {"changed": false, "dest": "/tmp", "failed": true, "gid": 0, "group": "root", "mode": "01777", "msg": "Request failed: <urlopen error [Errno -2] Name or service not known>", "owner": "root", "size": 4096, "state": "directory", "uid": 0, "url": "http://build-squid.eng.vmware.com/build/mts/release/bora-2459827/publish/VMware-ovftool-4.1.0-2459827-lin.x86_64.zip"}
```

**Comment by tompscanlan** [comment]
Unfortunately the ovftool requires an eula   signature to download.  That url works only inside vmware... you'll have to download it separately and host it in a local repository.

I'll add a better indication of what's happening in this case and also ask around for a better solution.

**Comment by tdhite** [comment]
We will have to use a rsync or similar solutions to go around the EULA download requirements. I'll add such code to the repos soon enough -- that will allow folks to download, place on a local machine (whatever their dev machine ends up being). That's effectively what we do with the code and repo anyway -- repo sync, run playbooks, the latter rsyncs the appropriate code to the apache site.
